### ISSUE TITLE
Question ::::: How To Set This Look And Feel To Any Apps/Jar

### ISSUE THREAD

**Issue by chezsick** [atarw/material-ui-swing#38]
Hi My Name Is Sick, I Not Success To Switch This Look And Feel From Command Line, For The Nimbus No Problem ::::: java -Dswing.defaultlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel -jar _MyApp_ But For This Look And Feel So Material Design No And I Try  java -classpath /path/to/material-ui-swing.jar -Dswing.defaultlaf=mdlaf.MaterialLookAndFeel -jar _MyApp_ Not Work

Thank You Sick.

**Comment by atarw** [comment]
Hmm, that is odd, it seems to work for me. I can't really debug without more information, but try adding the L&F to the program's class path, and then compiling everything and using the `-Dswing.defaultlaf` argument, since I think the `material-ui-swing.jar` file may not be getting compiled before the default L&F is set.

[For reference](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html))

**Comment by vincenzopalazzo** [comment]
Hello @chezsick ,
Can I try to say mine about the mistake ??
I think the error is in the declaration of the classpath, every declaration for an external jar must start for.: / directory (under linux and mac) and instead.; \ directory (for windows).
(although it should go without a point and directly with / directory but try it does not cost anything)
Let me know if you can solve this solution once.

I also tried to implement a jar of software published in the lecture of my university where the look was loaded and fell from a .conf file through an external software that facilitated the construction of MVC, in this software does not work the change of look and fell from the command line (at least in my case no, 'cause I also tried with a look and fell of the sun but the same error "Can not load ....")

Also I just noticed this little difference with the last versions, when it is rendered the theme I get this result, now I do not know if @atarw decided to change a bit but seeing the commits I think the bug was introduced by me now I try to take a look at the code and try to solve this problem

**Comment by chezsick** [comment]
@vincenzopalazzo Nothing I Try java -cp .:/to/path/material-ui-swing.jar -Dswing.defaultlaf=mdlaf.MaterialLookAndFeel -jar _myapp_

Not Work I See Errors Messages ::::
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.Error: Cannot load mdlaf.MaterialLookAndFeel
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1405)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1516)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1482)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1055)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
	at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:521)
	at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:348)
	at java.desktop/javax.swing.JFrame.createRootPane(JFrame.java:279)
	at java.desktop/javax.swing.JFrame.frameInit(JFrame.java:258)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:225)
	at com.ib.cryptimage.gui.MainGui.<init>(MainGui.java:306)
	at com.ib.cryptimage.core.Application.main(Application.java:34)
	... 5 more
```

**Comment by vincenzopalazzo** [comment]
la tua app usa il tema di default di java?

ed inoltre ti faccio una domanda stupida essendo un jar quindi inidipendende dal IDE perche' qui c'e' questo riferimento "at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)"??

**Comment by chezsick** [comment]
@vincenzopalazzo I Use CryptImage (Not At Github) So What IDE To Apply This L&F? Maven, Netbeans

And You Can Speak English Or French ??

**Comment by vincenzopalazzo** [comment]
@chezsick Excuse me it was a mistake of sitraction to publish the answer in my mother tongue, I'm sorry.

So you use this ... that would be a right framework ?? my question arises "And if the error is due to the same reason that was caused to me in my example"

**Comment by chezsick** [comment]
@vincenzopalazzo Good I Success Set This Look And Feel, But I Compile Self CryptImage :1st_place_medal:

**Comment by vincenzopalazzo** [comment]
@chezsick Good
